### ISSUE TITLE
About this

### ISSUE THREAD

**Issue by Dmunch04** [panda-lang/light#16]
Hi. Your project looks really cool. Is it supposed to be something like Skript? So a Minecraft plugin. If so, do you have a JAR file, or do I need to compile it myself?

Thanks,
Daniel

**Comment by dzikoysk** [comment]
Hey @Dmunch04,

The Light is independent programming language based on Panda Framework. Unfortunately, at this moment we are focused on Panda, Reposilite and panda-lang website to built whole environment structure. It's also required for Light to have these foundations. There are also some plans to support Minecraft (https://github.com/dzikoysk/lightmc <-- really old)

**Comment by Dmunch04** [comment]
Oh okay. The example just really looks like something from Skript. Well sounds cool. I'll keep an eye out!

Thanks

**Comment by dzikoysk** [comment]
The example in README is just a concept ofc. At this moment the syntax looks like https://github.com/panda-lang/light/blob/master/examples/current_test.light

I think that Light should get updates after release of alpha version of Panda.
